# Generated by Django 4.0 on 2022-01-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_event_registration_nevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_registration',
            new_name='sending',
        ),
    ]
