# Generated by Django 4.0 on 2022-01-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_send'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='send',
            new_name='load',
        ),
    ]
