# Generated by Django 4.0 on 2022-01-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_load_nopar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='load',
        ),
        migrations.DeleteModel(
            name='sending',
        ),
    ]
