# Generated by Django 4.0 on 2022-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_delete_load_delete_sending'),
    ]

    operations = [
        migrations.CreateModel(
            name='load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=244)),
                ('password', models.CharField(default='', max_length=122)),
                ('nopar', models.CharField(default='1', max_length=10)),
                ('nevent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nEvent', models.CharField(max_length=122)),
                ('desc', models.TextField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('deadline', models.DateField()),
                ('email', models.EmailField(default='', max_length=244)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
