# Generated by Django 4.0 on 2022-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='name',
            field=models.CharField(default='', max_length=122),
        ),
    ]
