# Generated by Django 4.0 on 2022-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_load_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sending',
            name='fname',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='sending',
            name='lname',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='sending',
            name='desc',
            field=models.TextField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='sending',
            name='location',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='sending',
            name='nEvent',
            field=models.CharField(default='', max_length=122),
        ),
    ]
