# Generated by Django 4.0 on 2022-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_load_nevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sending',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sending',
            name='lname',
        ),
        migrations.AlterField(
            model_name='load',
            name='nopar',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
