# Generated by Django 4.0 on 2022-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_fname_sending_name_remove_sending_lname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='nop',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='load',
            name='nopar',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
