# Generated by Django 4.0 on 2022-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_load_nop_sending_nop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='email',
            field=models.EmailField(default='', max_length=244, null=True),
        ),
    ]
