# Generated by Django 4.0 on 2022-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='email',
            field=models.EmailField(default='', max_length=244),
        ),
    ]
