# Generated by Django 4.0 on 2022-01-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_sending_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sending',
            old_name='email',
            new_name='host_email',
        ),
    ]
