# Generated by Django 4.0 on 2022-01-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_email_sending_host_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sending',
            new_name='Event_Registration',
        ),
    ]
